// solid-demo-todos/src/AddToDo.tsx
import { createSignal } from "solid-js";
import { useTodosApi } from "./dataprovider";

function AddToDo() {
  const [text, setText] = createSignal("");
  const { addToDo } = useTodosApi();
  

  function handleAddItem() {
    if (text().trim().length > 0) {
      addToDo({ isChecked: false, text: text() });
    }
    setText("");
  }

  return (
    <div class="flex flex-no-wrap">
      <div class="mr-2">
        <input class="py-1 px-3" type="text" oninput={(e) => setText(e.target.value)} value={text()} />
      </div>
      <div>
        <button class="px-3 py-1 bg-blue-300 hover:cursor-pointer hover:bg-blue-400 text-white" onclick={handleAddItem}>Add item</button>
      </div>
    </div>
  );
}

export default AddToDo;

// react-demo-todos/src/AddToDo.tsx
import React, { useRef, useState } from "react";
import { useTodosApi } from "./dataprovider";
import { countFnRender } from "./FunctionsRendersProvider";

function AddToDo() {
  countFnRender('AddToDo');
  const [text, setText] = useState("");
  const { addToDo } = useTodosApi();
  const refText = useRef(text);
  refText.current = text;

  function handleAddItem() {
    if (text.trim().length > 0) {
      addToDo({ isChecked: false, text });
    }
    setText("");
  }

  return (
    <div className="flex flex-no-wrap">
      <div className="mr-2">
        <input className="py-1 px-3" type="text" onInput={(e) => setText(e.currentTarget.value)} value={text} />
      </div>
      <div>
        <button className="px-3 py-1 bg-blue-300 hover:cursor-pointer hover:bg-blue-400 text-white" onClick={handleAddItem}>Add item</button>
      </div>
    </div>
  );
}

export default AddToDo;
