// react-demo-todos/src/TodoList.tsx
import React from "react";
import { ToDo} from "./dataprovider";
import ToDoItem from "./ToDoItem";
import { countFnRender } from "./FunctionsRendersProvider";

export default function ToDoList(props: { todos: ToDo[] }) {
  countFnRender("ToDoList");
  return (
    <div className="mb-4">
      {props.todos.length === 0 ? (
        <div className="text-gray-600 font-italic">No todo items yet</div>
      ) : (
        props.todos.map((todo) => <ToDoItem key={todo.id} todo={todo} />)
      )}
    </div>
  );
}

// solid-demo-todos/src/TodoList.tsx
import { Accessor, For } from "solid-js";
import { ToDo, useTodosApi } from "./dataprovider";
import ToDoItem from "./ToDoItem";
import { contFnRender } from "./FunctionsRendersProvider";

export default function ToDoList(props: { todos: Accessor<ToDo[]> }) {
  contFnRender("ToDoList");
  return (
    <div class="mb-4">
      {props.todos().length === 0 ? (
        <div class="text-gray-600 font-italic">No todo items yet</div>
      ) : (
        <For each={props.todos()}>{(todo) => <ToDoItem todo={todo} />}</For>
      )}
    </div>
  );
}
